### ISSUE TITLE
Add Notification service

### ISSUE THREAD

**Issue by mosoriob** [tapis-project/tapis-typescript#37]

**Comment by mosoriob** [comment]
WIP https://github.com/mosoriob/tapis-typescript/tree/37 🚧

**Comment by nathandf** [comment]
Also, I am happy to let you do it. Only thing I would ask is that you follow the Wiki below:
https://github.com/tapis-project/tapis-typescript/wiki/Publishing-New-Services-to-@tapis-tapis-typescript

As I said we are making many changes to TapisUI and TapisTypescript. Do not make any changes to the dependencies of the tapis-typescript package or any of the service sub packages. Thanks!

**Comment by mosoriob** [comment]
Hi, 

I'm working on it. I was following that wiki. 

Thanks

**Comment by mosoriob** [comment]
@nathandf, I have submitted the pull request. There are two pending tasks:

- [ ] [publishing] I didn't publish the notifications package because I don't have privileges in the npm organization.
- [ ] [e2e-test] I couldn't create a notification test because it only works for service accounts.

**Comment by mosoriob** [comment]
@nathandf I think there is a issue on the line

https://github.com/tapis-project/tapis-typescript/blob/main/tapis-typescript/package-lock.json#L18
